package com.personal.basemodel;

/**
 *
 * @author autogenerated
 */

public class BaseFacultyInfo {
	protected int facultyId;
	protected String year;
	protected String subject;
	protected String facultyName;
	protected String facultyPhotoPath;
	protected String aboutFaculty;
	protected String contact;
	protected String email;
	protected String updatedBy;
	protected String updatedDate;

	public String getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}

	

	public int getFacultyId() {
		return facultyId;
	}

	public void setFacultyId(int facultyId) {
		this.facultyId = facultyId;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getFacultyName() {
		return facultyName;
	}

	public void setFacultyName(String facultyName) {
		this.facultyName = facultyName;
	}

	public String getFacultyPhotoPath() {
		return facultyPhotoPath;
	}

	public void setFacultyPhotoPath(String facultyPhotoPath) {
		this.facultyPhotoPath = facultyPhotoPath;
	}

	public String getAboutFaculty() {
		return aboutFaculty;
	}

	public void setAboutFaculty(String aboutFaculty) {
		this.aboutFaculty = aboutFaculty;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}