package com.personal.basemodel;


import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 *
 * @author autogenerated
 */



public class BasePersonalInfo 
{

/** Field mapping. **/
@Column(name= "roll_no")
protected String rollNo ;

/** Field mapping. **/
@Column(name= "password")
protected String password ;

/** Field mapping. **/
@Column(name= "name")
protected String name ;

/** Field mapping. **/
@Column(name= "contact_no")
protected String contactNo ;

/** Field mapping. **/
@Column(name= "email")
protected String email ;

/** Field mapping. **/
@Column(name= "place_of_living")
protected String placeOfLiving ;

/** Field mapping. **/
@Column(name= "country")
protected String country ;

/** Field mapping. **/
@Column(name= "job_info")
protected String jobInfo ;

/** Field mapping. **/
@Column(name= "spouse_name")
protected String spouseName ;

/** Field mapping. **/
@Column(name= "spouse_job")
protected String spouseJob ;

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

public String getRollNo()
{
  return rollNo;
}
public void setRollNo(final String rollNo)
{
  this.rollNo = rollNo;
}
public String getPassword()
{
  return password;
}
public void setPassword(final String password)
{
  this.password = password;
}
public String getName()
{
  return name;
}
public void setName(final String name)
{
  this.name = name;
}
public String getContactNo()
{
  return contactNo;
}
public void setContactNo(final String contactNo)
{
  this.contactNo = contactNo;
}
public String getEmail()
{
  return email;
}
public void setEmail(final String email)
{
  this.email = email;
}
public String getPlaceOfLiving()
{
  return placeOfLiving;
}
public void setPlaceOfLiving(final String placeOfLiving)
{
  this.placeOfLiving = placeOfLiving;
}
public String getCountry()
{
  return country;
}
public void setCountry(final String country)
{
  this.country = country;
}
public String getJobInfo()
{
  return jobInfo;
}
public void setJobInfo(final String jobInfo)
{
  this.jobInfo = jobInfo;
}
public String getSpouseName()
{
  return spouseName;
}
public void setSpouseName(final String spouseName)
{
  this.spouseName = spouseName;
}
public String getSpouseJob()
{
  return spouseJob;
}
public void setSpouseJob(final String spouseJob)
{
  this.spouseJob = spouseJob;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}

}