package com.personal.basemodel;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;



import java.util.Date;
import java.math.BigDecimal;


/**
 *
 * @author autogenerated
 */



public class BaseFaculty 
{

/** Field mapping. **/
@Column(name= "year")
protected int year ;

/** Field mapping. **/
@Column(name= "subject")
protected String subject ;

/** Field mapping. **/
@Column(name= "faculty_Name")
protected String facultyName ;

/** Field mapping. **/
@Column(name= "faculty_Info")
protected String facultyInfo ;

/** Field mapping. **/
@Column(name= "role")
protected String role ;

/** Field mapping. **/
@Column(name= "updated_By")
protected String updatedBy ;

/** Field mapping. **/
@Column(name= "updated_On")
protected Date updatedOn ;

@Id
@GeneratedValue(strategy=GenerationType.AUTO)
		 /** Field mapping. **/
@Column(name= "id")
protected int id   = 0;

public int getYear()
{
  return year;
}
public void setYear(final int year)
{
  this.year = year;
}
public String getSubject()
{
  return subject;
}
public void setSubject(final String subject)
{
  this.subject = subject;
}
public String getFacultyName()
{
  return facultyName;
}
public void setFacultyName(final String facultyName)
{
  this.facultyName = facultyName;
}
public String getFacultyInfo()
{
  return facultyInfo;
}
public void setFacultyInfo(final String facultyInfo)
{
  this.facultyInfo = facultyInfo;
}
public String getRole()
{
  return role;
}
public void setRole(final String role)
{
  this.role = role;
}
public String getUpdatedBy()
{
  return updatedBy;
}
public void setUpdatedBy(final String updatedBy)
{
  this.updatedBy = updatedBy;
}
public Date getUpdatedOn()
{
  return updatedOn;
}
public void setUpdatedOn(final Date updatedOn)
{
  this.updatedOn = updatedOn;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}

}